# Generated by Django 3.2.8 on 2021-10-23 12:48

import apps.database.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Жанр')),
                ('color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Цвет')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('photo', models.FileField(upload_to='films/', validators=[apps.database.validators.photo_validator], verbose_name='Баннер')),
                ('year', models.IntegerField(verbose_name='Год премьеры')),
                ('description', models.TextField(verbose_name='Описание')),
                ('average_rating', models.FloatField(blank=True, null=True, verbose_name='Средняя оценка')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Удалено?')),
                ('actors', models.ManyToManyField(blank=True, related_name='films', to='database.Actor', verbose_name='Актеры')),
                ('genres', models.ManyToManyField(blank=True, related_name='films', to='database.Genre', verbose_name='Жанры')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('text', models.CharField(max_length=255, verbose_name='Текст')),
                ('ip', models.GenericIPAddressField(verbose_name='IP отправителя')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='database.film', verbose_name='Фильм')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], verbose_name='Оценка')),
                ('ip', models.GenericIPAddressField(verbose_name='IP отправителя')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='database.film', verbose_name='Фильм')),
            ],
            options={
                'unique_together': {('film', 'ip')},
            },
        ),
    ]
