# Generated by Django 3.2.8 on 2021-10-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='avatar',
            new_name='photo',
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фото')),
                ('films', models.ManyToManyField(related_name='actors', to='database.Film', verbose_name='Фильмы')),
            ],
        ),
    ]
