# Generated by Django 3.2.8 on 2021-10-22 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20211022_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='photo',
            field=models.FileField(upload_to='actor/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='film',
            name='photo',
            field=models.FileField(upload_to='films/', verbose_name='Баннер'),
        ),
    ]
