# Generated by Django 3.2.8 on 2021-10-23 18:55

import apps.database.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_comment_parent_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='photo',
        ),
        migrations.AddField(
            model_name='film',
            name='banner',
            field=models.FileField(default=1, upload_to=apps.database.validators.file_validator, validators=[apps.database.validators.photo_validator], verbose_name='Баннер'),
            preserve_default=False,
        ),
    ]
