# Generated by Django 3.2.8 on 2021-10-22 16:34

import apps.database.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20211022_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='photo',
            field=models.FileField(upload_to='actor/', validators=[apps.database.validators.photo_validator], verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='film',
            name='photo',
            field=models.FileField(upload_to='films/', validators=[apps.database.validators.photo_validator], verbose_name='Баннер'),
        ),
    ]
