# Generated by Django 3.2.8 on 2021-10-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20211022_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='films',
            field=models.ManyToManyField(blank=True, related_name='actors', to='database.Film', verbose_name='Фильмы'),
        ),
    ]
