# Generated by Django 3.2.8 on 2021-10-22 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_actor_films'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('1', 'Плохо'), ('2', 'Ниже среднего'), ('3', 'Средне'), ('4', 'Выше среднего'), ('5', 'Хорошо')], max_length=1, verbose_name='Оценка')),
                ('ip', models.GenericIPAddressField(verbose_name='IP отправителя')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.film', verbose_name='Фильм')),
            ],
            options={
                'unique_together': {('film', 'ip')},
            },
        ),
    ]
