# Generated by Django 3.2.8 on 2021-10-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_alter_rating_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='grade',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1, verbose_name='Оценка'),
        ),
    ]
