# Generated by Django 3.2.8 on 2021-10-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='grade',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2, verbose_name='Оценка'),
        ),
    ]
