# Generated by Django 3.2.8 on 2021-10-25 13:08

import apps.database.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_alter_rating_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='film',
            field=models.FileField(blank=True, upload_to=apps.database.validators.file_validator, validators=[apps.database.validators.video_validator], verbose_name='Фильмы'),
        ),
    ]
