# Generated by Django 3.2.8 on 2021-10-22 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_alter_film_average_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='database.film', verbose_name='Фильм'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='grade',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], verbose_name='Оценка'),
        ),
    ]
