# Generated by Django 3.2.8 on 2021-10-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_auto_20211022_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='average_rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Средняя оценка'),
        ),
    ]
