# Generated by Django 3.2.8 on 2021-10-22 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_alter_film_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='films',
        ),
        migrations.AddField(
            model_name='film',
            name='actors',
            field=models.ManyToManyField(blank=True, related_name='films', to='database.Actor', verbose_name='Фильмы'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('text', models.CharField(max_length=255, verbose_name='Текст')),
                ('ip', models.GenericIPAddressField(verbose_name='IP отправителя')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='database.film', verbose_name='Фильм')),
            ],
        ),
    ]
