# Generated by Django 3.2.8 on 2021-10-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20211022_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Жанр')),
                ('color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Цвет')),
            ],
        ),
        migrations.RemoveField(
            model_name='actor',
            name='photo',
        ),
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='films', to='database.Genre', verbose_name='Жанры'),
        ),
    ]
